const theme = {
  space: [0, 4, 8, 16, 32, 64, 128, 256, 512],
  fixSpace: [ "4px","6px","8px","12px","16px","20px","24px","32px","36px" ],
  fonts: {
    body: 'Arial, system-ui, -apple-system, BlinkMacSystemFont, "Helvetica Neue", sans-serif',
    heading: "Arial",
    monospace: "Menlo, monospace",
  },
  fontSizes: [12, 14, 16, 20, 24, 32, 48, 64, 96],
  fontWeights: {
    body: 400,
    heading: 700,
    bold: 700,
    thin: 100,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
  colors: {
    divvyblue: "#7dcbf0",
    background: "#fff",
    primary: "#5eb6ab",
    primaryLight: "#bff5ee", 
    hoverPrimary: "#81cec8",
    secondary: "#707070",
    hoverSecondary: "#919191",
    textSecondary: "#FFFFFF",
    primaryContrast: "#FFFFFF",
    hoverPrimaryContrast: "#F6F6F6",
    muted: "#707070",
    filterHigh: "#B65E5E",
    filterNeutral: "#5eb6ab",
    filterLow: "#B6AD66",
    danger: "#E03F32",
    hoverDanger: "#ed5e52",
    clear: "transparent",
    hoverClear: "#E2E2E280",
    success: "#28a745",
    warning: "#ffc107",
    info: "#17a2b8",
    light: "#f8f9fa",
    dark: "#343a40",
    textMuted: "#00000080",
  },
  styles: {
    a: {
      color: "primary",
    },
    pre: {
      fontFamily: "monospace",
      overflowX: "auto",
      code: {
        color: "inherit",
      },
    },
    code: {
      fontFamily: "monospace",
      fontSize: "inherit",
    },
    table: {
      width: "100%",
      borderCollapse: "separate",
      borderSpacing: 0,
    },
    th: {
      textAlign: "left",
      borderBottomStyle: "solid",
    },
    td: {
      textAlign: "left",
      borderBottomStyle: "solid",
    },
    img: {
      maxWidth: "100%",
    },
  },
  text: {
    appTitle: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "thin",
      fontSize: 5,
    },
    headline: {
      fontFamily: "body",
      fontSize: "6",
      fontWeight: "heavy",
      lineHeight: "0",
      letterSpacing: "0",
    },
    caps: {
      fontFamily: "body",
      fontSize: "1",
      fontWeight: "bold",
      lineHeight: "1",
      letterSpacing: "2",
      textTransform: "uppercase",
    },
    caption: {
      fontFamily: "body",
      fontSize: "1",
      fontWeight: "regular",
      fontStyle: "italic",
      lineHeight: "1",
      letterSpacing: "1",
    },
    sectionHeader: {
      fontFamily: "body",
      fontSize: "4",
      fontWeight: "bold",
      lineHeight: "0",
      letterSpacing: "0",
    },
    root: {
      fontFamily: "body",
      lineHeight: "body",
      fontWeight: "body",
    },
    h1: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: 4,
    },
    h2: {
      color: "primary",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: [2, 3, null, null],
    },
    h3: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: [1, 2, null, null],
    },
    h4: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: [0, 1, null, null],
    },
    h5: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: [0, 1, null, null],
    },
    h6: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "100",
      fontSize: [0, 1, null, null],
    },
    p: {
      color: "text",
      fontFamily: "body",
      fontWeight: "body",
      lineHeight: "body",
      fontSize: [0, 1, null, null],
    },
  },
};
export default theme;
